services:
  backend:
    build: ./backend
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - "3698:5000"
    env_file:
      - .env
  frontend:
    build: ./frontend26
    ports:
      - "3699:80"
    env_file:
      - .env
